# docker-compose.yml

version: "3.7"
services:

  examma-ray-server:
    build:
      context: .
    command: "wait-for-it db:5432 -- bash -c \"npm run migrate && node ./build/server.js\""
    restart: always
    environment:
      DB_NAME: exammaray
      DB_USER: exammaray
      DB_HOST: db
      DB_PORT: 5432
      NODE_ENV: production
    secrets:
      - db_password
      - jwt_secret
      - google_client_secret

    depends_on:
      - db
    ports:
      - '127.0.0.1:3000:3000'
    volumes:
      - ./data:/usr/src/app/data
      - ./out:/usr/src/app/out
      - ./uploads:/usr/src/app/uploads
    networks:
        - http
        - db

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: exammaray
      POSTGRES_DB: exammaray
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
    secrets:
      - db_password
    ports:
      - '127.0.0.1:5000:5432'
    volumes:
      - examma-ray-db:/var/lib/postgresql/data
    networks:
      - db

  caddy:
    image: caddy:2.4.6
    restart: always
    volumes:
      - ./public:/public
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - http
    ports:
      - "80:80"
      - "443:443"
        
volumes:
  examma-ray-db:
  caddy_data:
  caddy_config:

networks:
  http:
  db:

secrets:
  db_password:
      file: ./secrets/db_password
  jwt_secret:
      file: ./secrets/jwt_secret
  google_client_secret:
      file: ./secrets/google_client_secret
